In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
#groups
g94 = pd.read_csv('groups_94.csv', sep=';')
g94 = g94[g94.LANGUAGE_ID.str.contains('EL')]
g94=g94.rename(columns={'ID':'GROUP_ID'})
g94

,GROUP_ID,LANGUAGE_ID,ACRONYM,LABEL
6,GP0601,EL,PSE,Ομάδα του Ευρωπαϊκού Σοσιαλιστικού Κόμματος
30,GP0602,EL,PPE,Ομάδα του Ευρωπαϊκού Λαϊκού Κόμματος (Χριστιαν...
54,GP0603,EL,ELDR,Ομάδα του Ευρωπαϊκού Κόμματος των Φιλελευθέρων...
78,GP0604,EL,GUE,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...
102,GP0605,EL,FE,Ομάδα Forza Europa
126,GP0606,EL,RDE,Ομάδα Συνασπισμού των Ευρωπαίων Δημοκρατών
150,GP0607,EL,V,Ομάδα των Πρασίνων στο Ευρωπαϊκό Κοινοβούλιο
174,GP0608,EL,ARE,Ομάδα της Ευρωπαϊκής Ριζοσπαστικής Συμμαχίας
198,GP0609,EL,EDN,Ομάδα Ευρώπη των Εθνών (Ομάδα συντονισμού)
222,NaN,EL,NI,Μη Εγγεγραμμένοι

In [3]:
p94 = pd.read_csv('parties_94.csv', sep=';')
p94 = p94[['DIVISION_ID','ID','ACRONYM','LABEL']].copy()
p94 = p94[p94.DIVISION_ID.str.contains('EL')]
p94 = p94.rename(columns={'ID':'PARTY_ID'})
p94

,DIVISION_ID,PARTY_ID,ACRONYM,LABEL
49,EL,EL01,PASOK,Panellinio Sosialistiko Kinima
50,EL,EL02,N.D.,Nea Dhimokratia
51,EL,EL03,KKE,Kommunistiko Komma Elladas
52,EL,EL04,SYN,Synaspismos tis aristeras kai tis proodou
53,EL,EL05,POL.AN,Politiki Anoixi
54,EL,EL90,Other parties,Other parties

In [4]:
omada94 = pd.read_csv('el_94.csv', sep=';')
omada94=omada94[['GROUP_ID','SEATS_TOTAL','SEATS_PERCENT_EU']].copy()
omada94

  GROUP_ID  SEATS_TOTAL  SEATS_PERCENT_EU
0   GP0601           10              1.76
1   GP0602            9              1.59
2   GP0603            0              0.00
3   GP0604            4              0.71
4   GP0605            0              0.00
5   GP0606            2              0.35
6   GP0607            0              0.00
7   GP0608            0              0.00
8   GP0609            0              0.00
9      NaN            0              0.00

In [5]:
ethniko_komma = pd.read_csv('results-parties-el_94.csv', sep=';')
ethniko_komma

  PARTY_ID   TYPE  VOTES_PERCENT UPDATE_STATUS  UPDATE_TIME
0     EL01  PARTY            NaN         FINAL          NaN
1     EL02  PARTY            NaN         FINAL          NaN
2     EL03  PARTY            NaN         FINAL          NaN
3     EL04  PARTY            NaN         FINAL          NaN
4     EL05  PARTY            NaN         FINAL          NaN
5     EL90  PARTY            NaN         FINAL          NaN

In [5]:
katataksh94 = pd.read_csv('katataksh_94.csv', sep=';')
katataksh94

  PARTY_ID   TYPE  SEATS_TOTAL GROUP_ID UPDATE_STATUS  UPDATE_TIME
0     EL01  PARTY           10   GP0601  CONSTITUTIVE          NaN
1     EL02  PARTY            9   GP0602  CONSTITUTIVE          NaN
2     EL03  PARTY            2   GP0604  CONSTITUTIVE          NaN
3     EL04  PARTY            2   GP0604  CONSTITUTIVE          NaN
4     EL05  PARTY            2   GP0606  CONSTITUTIVE          NaN

In [6]:
df94=pd.merge(katataksh94, omada94, on='GROUP_ID', how='outer')
df94

,PARTY_ID,TYPE,SEATS_TOTAL_x,GROUP_ID,UPDATE_STATUS,UPDATE_TIME,SEATS_TOTAL_y,SEATS_PERCENT_EU
0,EL01,PARTY,10.0,GP0601,CONSTITUTIVE,NaN,10,1.76
1,EL02,PARTY,9.0,GP0602,CONSTITUTIVE,NaN,9,1.59
2,EL03,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4,0.71
3,EL04,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4,0.71
4,EL05,PARTY,2.0,GP0606,CONSTITUTIVE,NaN,2,0.35
5,NaN,NaN,NaN,GP0603,NaN,NaN,0,0.00
6,NaN,NaN,NaN,GP0605,NaN,NaN,0,0.00
7,NaN,NaN,NaN,GP0607,NaN,NaN,0,0.00
8,NaN,NaN,NaN,GP0608,NaN,NaN,0,0.00
9,NaN,NaN,NaN,GP0609,NaN,NaN,0,0.00
10,NaN,NaN,NaN,NaN,NaN,NaN,0,0.00

In [7]:
df94=pd.merge(df94, g94, on='GROUP_ID', how='outer')
df94

,PARTY_ID,TYPE,SEATS_TOTAL_x,GROUP_ID,UPDATE_STATUS,UPDATE_TIME,SEATS_TOTAL_y,SEATS_PERCENT_EU,LANGUAGE_ID,ACRONYM,LABEL
0,EL01,PARTY,10.0,GP0601,CONSTITUTIVE,NaN,10,1.76,EL,PSE,Ομάδα του Ευρωπαϊκού Σοσιαλιστικού Κόμματος
1,EL02,PARTY,9.0,GP0602,CONSTITUTIVE,NaN,9,1.59,EL,PPE,Ομάδα του Ευρωπαϊκού Λαϊκού Κόμματος (Χριστιαν...
2,EL03,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4,0.71,EL,GUE,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...
3,EL04,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4,0.71,EL,GUE,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...
4,EL05,PARTY,2.0,GP0606,CONSTITUTIVE,NaN,2,0.35,EL,RDE,Ομάδα Συνασπισμού των Ευρωπαίων Δημοκρατών
5,NaN,NaN,NaN,GP0603,NaN,NaN,0,0.00,EL,ELDR,Ομάδα του Ευρωπαϊκού Κόμματος των Φιλελευθέρων...
6,NaN,NaN,NaN,GP0605,NaN,NaN,0,0.00,EL,FE,Ομάδα Forza Europa
7,NaN,NaN,NaN,GP0607,NaN,NaN,0,0.00,EL,V,Ομάδα των Πρασίνων στο Ευρωπαϊκό Κοινοβούλιο
8,NaN,NaN,NaN,GP0608,NaN,NaN,0,0.00,EL,ARE,Ομάδα της Ευρωπαϊκής Ριζοσπαστικής Συμμαχίας
9,NaN,NaN,NaN,GP0609,NaN,NaN,0,0.00,EL,EDN,Ομάδα Ευρώπη των Εθνών (Ομάδα συντονισμού)
10,NaN,NaN,NaN,NaN,NaN,NaN,0,0.00,EL,NI,Μη Εγγεγραμμένοι

In [8]:
df94=pd.merge(df94, p94, on='PARTY_ID', how='outer')
df94

,PARTY_ID,TYPE,SEATS_TOTAL_x,GROUP_ID,UPDATE_STATUS,UPDATE_TIME,SEATS_TOTAL_y,SEATS_PERCENT_EU,LANGUAGE_ID,ACRONYM_x,LABEL_x,DIVISION_ID,ACRONYM_y,LABEL_y
0,EL01,PARTY,10.0,GP0601,CONSTITUTIVE,NaN,10.0,1.76,EL,PSE,Ομάδα του Ευρωπαϊκού Σοσιαλιστικού Κόμματος,EL,PASOK,Panellinio Sosialistiko Kinima
1,EL02,PARTY,9.0,GP0602,CONSTITUTIVE,NaN,9.0,1.59,EL,PPE,Ομάδα του Ευρωπαϊκού Λαϊκού Κόμματος (Χριστιαν...,EL,N.D.,Nea Dhimokratia
2,EL03,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4.0,0.71,EL,GUE,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...,EL,KKE,Kommunistiko Komma Elladas
3,EL04,PARTY,2.0,GP0604,CONSTITUTIVE,NaN,4.0,0.71,EL,GUE,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...,EL,SYN,Synaspismos tis aristeras kai tis proodou
4,EL05,PARTY,2.0,GP0606,CONSTITUTIVE,NaN,2.0,0.35,EL,RDE,Ομάδα Συνασπισμού των Ευρωπαίων Δημοκρατών,EL,POL.AN,Politiki Anoixi
5,NaN,NaN,NaN,GP0603,NaN,NaN,0.0,0.00,EL,ELDR,Ομάδα του Ευρωπαϊκού Κόμματος των Φιλελευθέρων...,NaN,NaN,NaN
6,NaN,NaN,NaN,GP0605,NaN,NaN,0.0,0.00,EL,FE,Ομάδα Forza Europa,NaN,NaN,NaN
7,NaN,NaN,NaN,GP0607,NaN,NaN,0.0,0.00,EL,V,Ομάδα των Πρασίνων στο Ευρωπαϊκό Κοινοβούλιο,NaN,NaN,NaN
8,NaN,NaN,NaN,GP0608,NaN,NaN,0.0,0.00,EL,ARE,Ομάδα της Ευρωπαϊκής Ριζοσπαστικής Συμμαχίας,NaN,NaN,NaN
9,NaN,NaN,NaN,GP0609,NaN,NaN,0.0,0.00,EL,EDN,Ομάδα Ευρώπη των Εθνών (Ομάδα συντονισμού),NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,EL,NI,Μη Εγγεγραμμένοι,NaN,NaN,NaN
11,EL90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EL,Other parties,Other parties

In [10]:
df94=df94[['PARTY_ID','SEATS_TOTAL_x','GROUP_ID','SEATS_TOTAL_y','SEATS_PERCENT_EU','LABEL_x','LABEL_y']].copy()
df94

,PARTY_ID,SEATS_TOTAL_x,GROUP_ID,SEATS_TOTAL_y,SEATS_PERCENT_EU,LABEL_x,LABEL_y
0,EL01,10.0,GP0601,10.0,1.76,Ομάδα του Ευρωπαϊκού Σοσιαλιστικού Κόμματος,Panellinio Sosialistiko Kinima
1,EL02,9.0,GP0602,9.0,1.59,Ομάδα του Ευρωπαϊκού Λαϊκού Κόμματος (Χριστιαν...,Nea Dhimokratia
2,EL03,2.0,GP0604,4.0,0.71,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...,Kommunistiko Komma Elladas
3,EL04,2.0,GP0604,4.0,0.71,Συνομοσπονδιακή Ομάδα της Ευρωπαϊκής Ενωτικής ...,Synaspismos tis aristeras kai tis proodou
4,EL05,2.0,GP0606,2.0,0.35,Ομάδα Συνασπισμού των Ευρωπαίων Δημοκρατών,Politiki Anoixi
5,NaN,NaN,GP0603,0.0,0.00,Ομάδα του Ευρωπαϊκού Κόμματος των Φιλελευθέρων...,NaN
6,NaN,NaN,GP0605,0.0,0.00,Ομάδα Forza Europa,NaN
7,NaN,NaN,GP0607,0.0,0.00,Ομάδα των Πρασίνων στο Ευρωπαϊκό Κοινοβούλιο,NaN
8,NaN,NaN,GP0608,0.0,0.00,Ομάδα της Ευρωπαϊκής Ριζοσπαστικής Συμμαχίας,NaN
9,NaN,NaN,GP0609,0.0,0.00,Ομάδα Ευρώπη των Εθνών (Ομάδα συντονισμού),NaN
10,NaN,NaN,NaN,0.0,0.00,Μη Εγγεγραμμένοι,NaN
11,EL90,NaN,NaN,NaN,NaN,NaN,Other parties